server:
  servlet:
    context-path: /springbootshiro
spring:
  profiles:
    active: 8081
  mvc:
    view:
      prefix: classpath:/templates/ #定义视图解析器的规则，文件前缀
      suffix: .html #定义视图解析器的规则，文件后缀

---
spring:
  profiles: 8081
server:
  port: 8081

---
spring:
  profiles: 8082
server:
  port: 8082